<a href="https://colab.research.google.com/github/Vcetpreeti/DS_internship/blob/main/Copy_of_DAY1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
X=5
M=6
Y="9"
z="2"
print(type(X))
print(type(Y))
print(type(M))
print(type(z))
print(type(Y+z))
print(Y+z)
print(X+M)
a=int(z)
print(a+M)

#list
l1=['hii','12','list','preeti',[9.5,'56','yes']]
l2=l1[4][2]
print(l2)
print(len(l2))
print(type(l1))
nums=[]
nums.append(34)
nums.append('preeti')
nums.append(67.5)
print(nums)
#tuple
t1=()
print(type(t1))
#dictionary
d1={'name':'preeti','age':12,'salary':1200}
print(d1)
print(type(d1))
print(d1.keys())
print(d1.items())
print(d1.values())
print(d1['age'])
#input
x=int(input("enter num1:"))
y=int(input("enter num2:"))
print(x*y)
if 34>x:
  print("number is good")
elif 34<y:
  print("numberis not good")
else:
 print("number is okayyish")
#NumPy
import numpy as np
arr=np.array((1,2,3))
print("array with rank 2:",arr)
print(type(arr))
print("array size:",arr.size)
#view
#copy
#def
#base function to get the original value
import pandas as pd
mydataset={
    'cars':['bmw',"mercedes","porcshe"],
    'passings':[3,4,5]
}



<class 'int'>
<class 'str'>
<class 'int'>
<class 'str'>
<class 'str'>
92
11
8
yes
3
<class 'list'>
[34, 'preeti', 67.5]
<class 'tuple'>
{'name': 'preeti', 'age': 12, 'salary': 1200}
<class 'dict'>
dict_keys(['name', 'age', 'salary'])
dict_items([('name', 'preeti'), ('age', 12), ('salary', 1200)])
dict_values(['preeti', 12, 1200])
12
enter num1:3
enter num2:6
18
number is good
array with rank 2: [1 2 3]
<class 'numpy.ndarray'>
array size: 3


In [ ]:
import numpy as np
#In this example, we are creating a two-dimensional array that has the rank of 2 as it has 2 axes.
#The first axis(dimension) is of length 2, i.e., the number of rows, and the second axis(dimension) is of length 3,
#i.e., the number of columns. The overall shape of the array can be represented as (2, 3)
# Creating array object
arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)



Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [ ]:
#Python program for
# Creation of Arrays
import numpy as np

# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)

# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)


Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [ ]:
import numpy as np

# creating array
arr = np.array([2, 4, 6, 8, 10])

# creating copy of array
c = arr.copy()

# both arr and c have different id
print("id of arr", id(arr))
print("id of c", id(c))

# changing original array
# this will not effect copy
arr[0] = 12

# printing array and copy
print("original array- ", arr)
print("copy- ", c)



id of arr 135931302520432
id of c 135931302520720
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


In [ ]:
# Let's define our function
# Parameters: Input Array
def sum(array):

	# Set variable for our final answer
	sum = 0

	# Parse through our array
	for i in array:

		# Continuously add current element
		# to final sum
		sum += i

	# Return our sum
	return sum


# Create a test array
testArray = [1, 3, 34, 92, 29, 48, 20.3]

# Test our function
print('The sum of your numbers is ' + str(sum(testArray)))


The sum of your numbers is 227.3


In [ ]:
import numpy as np
# Create a sequence of integers from 10 to 1 with a step of -2
a = np.arange(10, 1, -2)
print("\n A sequential array with a negative step: \n",a)
# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [ ]:
#A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)


#Pandas use the loc attribute to return one or more specified row(s)
#refer to the row index:
print(df.loc[0])
#Returns a pandas series


#use a list of indexes:
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40
